import { createGlIllustrationOverlayA, createGlIllustrationOverlayB } from "../views/templates/template-creator";
import actions from "./tutorial-actions";

const tutorialData = {
  city01: {
    1: { // Level 1
      1: [ // Step id
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => setTimeout(() => actions.focus(next, ['.gl-progress-bar']), 1000) },
        { action: (next) => setTimeout(() => actions.showGuide(next, '.gl-progress-bar', 'Ini adalah bar kemajuan kamu! <br> Jawab soal dengan benar untuk mendapatkan air! 💧 <br> Semakin banyak air, tanamanmu akan semakin tumbuh besar!', ['0', 'unset']), 1000) },
        { action: (next) => actions.showGuide(next, '.gl-progress-bar', 'Lingkaran ini menunjukkan langkah yang sedang kamu kerjakan.', ['unset', '0']) },
        { action: (next) => actions.focus(next, ['.main-quiz']) },
        { action: (next) => setTimeout(() => actions.showGuide(next, '.main-quiz', 'Soal kuis utama. Baca dan pahami sebelum mengerjakan!', ['0', 'unset']), 1000) },
        { action: (next) => actions.focus(next, ['.sub-quiz']) },
        { action: (next) => setTimeout(() => actions.showGuide(next, '.sub-quiz', 'Setiap soal punya beberapa langkah yang harus kamu kerjakan.', ['0', 'unset']), 1000) },
        { action: (next) => actions.showPrecisWrapper(next) },
        { action: (next) => actions.focus(next, ['.precis-wrapper']) },
        { action: (next) => setTimeout(() => actions.highlight(next, '.known', 0), 1000) },
        { action: (next) => {
          const mainQuiz = (JSON.parse(sessionStorage.getItem('detailQuiz'))).main;
          const tutorialQuiz = mainQuiz[0];
          setTimeout(() => actions.showPrecis(next, tutorialQuiz.precis, 0), 1000); 
        } },
        { action: (next) => setTimeout(() => actions.highlight(next, '.known', 1), 2000) },
        { action: (next) => {
          const mainQuiz = (JSON.parse(sessionStorage.getItem('detailQuiz'))).main;
          const tutorialQuiz = mainQuiz[0];
          setTimeout(() => actions.showPrecis(next, tutorialQuiz.precis, 1), 1000);
        } },
        { action: (next) => setTimeout(() => actions.showGuide(next, '.precis-wrapper', 'Catat informasi penting dari soal.', ['unset', '0']), 1000) },
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => actions.unfocus(next) },
        { action: (next) => actions.focusInput(next, '#firstNum') },
        { action: (next) => setTimeout(() => actions.showPointer(next, '.btn-fraction', 'Aktifkan mode pecahan', '.result', '30px', true), 2000) },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction']) },
        { action: (next) => actions.showPointer(next, '2', 'Masukkan angka perkalian') },
        { action: (next) => actions.showPointer(next, '.first-fraction__denominator') },
        { action: (next) => actions.showPointer(next, '3') },
        { action: (next) => actions.showPointer(next, '.second-number') },
        { action: (next) => actions.showPointer(next, '5') },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction']) },
        { action: (next) => actions.showPointer(next, '.btn-submit-result__container', 'Submit Jawaban') },
      ],
      2: [
        { action: (next) => actions.removeHighlight(next) },
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => actions.focus(next, ['.gl-progress-bar .gl-minor-progress']) },
        { action: (next) => actions.showGuide(next, '.gl-minor-progress', 'Jawabanmu benar! Air didapat dan tanamanmu berkembang! 🎉', ['unset', '0']) },
        { action: (next) => actions.focus(next, ['.gl-progress-bar', '.main-quiz', '.sub-quiz']) },
        { action: (next) => actions.focus(next, ['.multiplication-pair']) },
        { action: (next) => setTimeout(() => actions.showArrowMultiplication(next, '.multiplication-pair', 'top'), 2000) },
        { action: (next) => setTimeout(() => actions.showClue(next, 'Kalikan angka atas dengan 5. <span class="multiplication">2 x 5 = 10</span>', '.result .calc-input', ['unset', '100%']), 1000) },
        { action: (next) => setTimeout(() => actions.showGuide(next, '.tutorial-clue', 'Perhatikan cara mengerjakannya.', ['unset', '0']), 2000) },
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => actions.focusInput(next, '#numerator') },
        { action: (next) => setTimeout(() => actions.showPointer(next, '1', 'Masukkan hasil perkalian', '.result', '30px', true), 1000)},
        { action: (next) => actions.showPointer(next, '0')},
        { action: (next) => actions.removeElement(next, ['.tutorial-clue', '.curved-line', '.tutorial-instruction']) },
        { action: (next) => setTimeout(() => actions.showClue(next, 'Berikan angka penyebut ke hasil', '.result .calc-input', ['unset', '100%']), 1000) },
        { action: (next) => actions.showArrowMultiplication(next, '.multiplication-pair', 'bottom') },
        { action: (next) => actions.showPointer(next, '.first-fraction__denominator') },
        { action: (next) => actions.showPointer(next, '3') },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue', '.right-arrow_multiplication', '.tutorial-instruction']) },
        { action: (next) => actions.showPointer(next, '.btn-submit-result__container', 'Submit Jawaban') },
      ],
      3: [
        { action: (next) => actions.unfocus(next) },
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => actions.focus(next, ['.sub-quiz', '.fraction.result']) },
        { action: (next) => setTimeout(() => actions.showClue(next, 'Kalau angka atas dan bawah bisa dibagi dengan angka yang sama, pecahan bisa disederhanakan. <br> Kalau tidak bisa, berarti sudah paling sederhana ya!', '.result', ['unset', '50px']), 2000) },
        { action: (next) => actions.addBtnNext(next, '.tutorial-clue') },
        { action: (next) => actions.showClue(next, '10 dan 3 tidak bisa dibagi dengan angka yang sama (selain 1). <br> Artinya… pecahannya sudah paling sederhana!', '.result', ['85px', '-60px']) },
        { action: (next) => actions.addBtnNext(next, '.tutorial-clue:last-child') },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue:first-child', '.tutorial-clue:last-child']) },
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => actions.showPointer(next, '.answer-choices .no', 'Pilih jawaban yang tepat.') }
      ],
      5: [
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => actions.focus(next, ['.sub-quiz', '.fraction.result', '.fraction-unit']) },
        { action: (next) => setTimeout(() => actions.showClue(next, 'Yuk bayangkan! <br>Satu keranjang isi 3 bagian.', '.result', ['0', '60px']), 2000) },
        { action: (next) => setTimeout(() => actions.showClue(next, 'Kamu punya 10 bagian buah!', '.result', ['90px', '70px']), 3000) },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.tutorial-clue:last-child', 'Lanjut'), 1500) },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue__wrapper']) },
        { action: (next) => actions.showClue(next, 'Hasilnya:', '.result', ['0', '60px']) },
        // { action: (next) => actions.addBtnNext(next, '.tutorial-clue:last-child', 'Lanjut') },
        // { action: (next) => actions.removeElement(next, ['.tutorial-clue__wrapper']) },
        { action: (next) => setTimeout(() => actions.showClue(next, '3 keranjang penuh', '.result', ['60px', '70px']), 1000) },
        { action: (next) => setTimeout(() => actions.showIllustrationContainer(next), 1500) },
        { action: (next) => setTimeout(() => actions.addItemToContainer(next, '.illustration-container', '<img src="./illustrations-quiz/gl-il-1.png">'), 1500) },
        { action: (next) => setTimeout(() => actions.addItemToContainer(next, '.illustration-container', '<img src="./illustrations-quiz/gl-il-1.png">'), 1000) },
        { action: (next) => setTimeout(() => actions.addItemToContainer(next, '.illustration-container', '<img src="./illustrations-quiz/gl-il-1.png">'), 1000) },
        { action: (next) => setTimeout(() => actions.showClue(next, '1 keranjang isi 1 bagian', '.result', ['140px', '70px']), 1500) },
        { action: (next) => setTimeout(() => actions.addItemToContainer(next, '.illustration-container', '<img src="./illustrations-quiz/gl-il-2.png">'), 1500) },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.tutorial-clue:last-child', 'Lanjut') , 1000) },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue__wrapper']) },
        { action: (next) => actions.showClue(next, 'Jadi, 10 bagian = 3 keranjang penuh + 1 bagian', '.result', ['0', '60px']) },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.tutorial-clue:last-child') , 1000) },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue__wrapper', '.illustration-container']) },
        { action: (next) => actions.unfocus(next, ['.fraction.result', '.item-name']) },
        { action: (next) => actions.focus(next, ['.open-image-btn']) },
        { action: (next) => actions.showPointer(next, '.open-image-btn.first', 'Klik kaca pembesar untuk melihat gambar ukuran penuh') },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction']) },
        { action: (next) => actions.hideElement(next, '#imageModal .close-btn') },
        { action: (next) => setTimeout(() => actions.showDialog(next, '.modal-content', 'Apakah ilustrasi ini menggambarkan 10/3 keranjang buah?', 'top'), 1500) },
        { action: (next) => setTimeout(() => actions.showDialog(next, '.modal-content', 'Ayo cek bersama!', 'bottom'), 2000) },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.dialog-tutorial.bottom', 'Oke, mulai!'), 1500) },
        { action: (next) => actions.addOverlay(next, '.modal-content', createGlIllustrationOverlayA()) },
        { action: (next) => actions.showAllElementsGradually(next, '.number-counter span:not(.empty)') },
        { action: (next) => setTimeout(() => actions.showDialog(next, '.modal-content', 'Gambar di atas menunjukkan ada 11 bagian. Setiap keranjang berisi 3 bagian. <br>Jadi, pecahannya adalah 11/3.', 'bottom'), 1500) },
        { action: (next) => setTimeout(() => actions.showArrowNextBtn(next, '.dialog-tutorial.bottom'), 2000) },
        { action: (next) => actions.removeElement(next, ['.dialog-tutorial.bottom']) },
        { action: (next) => actions.showDialog(next, '.modal-content', 'Sehingga ilustrasi di atas bukan jawaban yang tepat.', 'bottom') },
        { action: (next) => setTimeout(() => actions.showElement(next, '#imageModal .close-btn'), 2000) },
        { action: (next) => actions.showPointer(next, '.close-btn', 'Klik untuk menutup detail gambar.', '.finger-container') },
        { action: (next) => actions.removeElement(next, ['.dialog-tutorial', '.illustration-overlay']) },
        { action: (next) => actions.unfocus(next) },
        { action: (next) => actions.focus(next, ['.open-image-btn.second']) },
        { action: (next) => actions.showPointer(next, '.open-image-btn.second', 'Klik kaca pembesar untuk melihat gambar lebih detail') },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction']) },
        { action: (next) => actions.hideElement(next, '#imageModal .close-btn') },
        { action: (next) => setTimeout(() => actions.showDialog(next, '.modal-content', 'Apakah ilustrasi ini menggambarkan 10/3 keranjang buah?', 'top'), 1500) },
        { action: (next) => setTimeout(() => actions.showDialog(next, '.modal-content', 'Ayo cek bersama!', 'bottom'), 2000) },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.dialog-tutorial.bottom', 'Oke, mulai!'), 1500) },
        { action: (next) => actions.addOverlay(next, '.modal-content', createGlIllustrationOverlayB()) },
        { action: (next) => actions.showAllElementsGradually(next, '.number-counter span:not(.empty)') },
        { action: (next) => setTimeout(() => actions.showDialog(next, '.modal-content', 'Gambar di atas menunjukkan ada 10 bagian. Setiap keranjang berisi 3 bagian. <br> Jadi, pecahannya adalah 10/3.', 'bottom'), 1500) },
        { action: (next) => setTimeout(() => actions.showArrowNextBtn(next, '.dialog-tutorial.bottom'), 2000) },
        { action: (next) => actions.removeElement(next, ['.dialog-tutorial.bottom']) },
        { action: (next) => actions.showDialog(next, '.modal-content', 'Ilustrasi di atas adalah jawaban yang tepat!', 'bottom') },
        { action: (next) => setTimeout(() => actions.showElement(next, '#imageModal .close-btn'), 2000) },
        { action: (next) => actions.showPointer(next, '.close-btn', 'Klik untuk menutup detail gambar.', '.finger-container') },
        { action: (next) => actions.removeElement(next, ['.dialog-tutorial', '.illustration-overlay']) },
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => actions.showPointer(next, '.answer-choices .option-b', 'Pilih jawaban yang tepat.', '.result', '120px') }
      ]
    },
    2: { // Level 2
      7: [ // Step 1
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => setTimeout(() => actions.focus(next, ['.gl-progress-bar']), 1000) },
        { action: (next) => setTimeout(() => actions.showGuide(next, '.gl-progress-bar', 'Di level ini, kamu akan mengumpulkan <b>jamur</b>. <br>Jawab soal dengan benar untuk mendapatkan <b>spora</b>. <br>Kumpulkan spora agar jamur kamu naik level! ', ['0', 'unset']), 1000) },
        { action: (next) => actions.showGuide(next, '.gl-progress-bar', 'Lingkaran ini menunjukkan langkah yang sedang kamu kerjakan.', ['unset', '0']) },
        { action: (next) => actions.focus(next, ['.main-quiz']) },
        { action: (next) => setTimeout(() => actions.showGuide(next, '.main-quiz', 'Soal kuis utama. Baca dan pahami sebelum mengerjakan!', ['0', 'unset']), 1000) },
        { action: (next) => actions.focus(next, ['.sub-quiz']) },
        { action: (next) => setTimeout(() => actions.showGuide(next, '.sub-quiz', 'Setiap soal punya beberapa langkah yang harus kamu kerjakan.', ['0', 'unset']), 1000) },
        { action: (next) => actions.showPrecisWrapper(next) },
        { action: (next) => actions.focus(next, ['.precis-wrapper']) },
        { action: (next) => setTimeout(() => actions.highlight(next, '.known', 0), 1000) },
        { action: (next) => {
          const mainQuiz = (JSON.parse(sessionStorage.getItem('detailQuiz'))).main;
          const tutorialQuiz = mainQuiz[0];
          setTimeout(() => actions.showPrecis(next, tutorialQuiz.precis, 0), 1000); 
        } },
        { action: (next) => setTimeout(() => actions.highlight(next, '.known', 1), 2000) },
        { action: (next) => {
          const mainQuiz = (JSON.parse(sessionStorage.getItem('detailQuiz'))).main;
          const tutorialQuiz = mainQuiz[0];
          setTimeout(() => actions.showPrecis(next, tutorialQuiz.precis, 1), 1000); 
        } },
        { action: (next) => setTimeout(() => actions.showGuide(next, '.precis-wrapper', 'Catat informasi penting dari soal.', ['unset', '0']), 1000) },
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => actions.unfocus(next) },
        { action: (next) => actions.showPointer(next, '.first-number', 'Masukkan angka pembagian') },
        { action: (next) => actions.showPointer(next, '2') },
        { action: (next) => actions.showPointer(next, '.second-number') },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction']) },
        { action: (next) => actions.showPointer(next, '.btn-fraction', 'Aktifkan mode pecahan', '.result', '30px') },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction']) },
        { action: (next) => actions.showPointer(next, '1') },
        { action: (next) => actions.showPointer(next, '.second-fraction__denominator', 'Masukkan angka', '.result', '50px') },
        { action: (next) => actions.showPointer(next, '2') },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction']) },
        { action: (next) => actions.showPointer(next, '.btn-submit-result__container', 'Submit Jawaban') },
      ],
      8: [
        { action: (next) => actions.removeHighlight(next) },
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => actions.focus(next, ['.gl-progress-bar .gl-minor-progress']) },
        { action: (next) => actions.showGuide(next, '.gl-minor-progress', 'Jawabanmu benar! Spora didapat dan jamurmu meningkat! 🎉', ['unset', '0']) },
        { action: (next) => actions.focus(next, ['.sub-quiz', '.division-pair']) },
        { action: (next) => setTimeout(() => actions.showClue(next, 'Untuk mengubah menjadi perkalian, balik pecahan pembagi. Yang atas menjadi di bawah, dan bawah menjadi di atas.', '.result .calc-input', ['unset', 'calc(100% + 80px)']), 1000) },
        { action: (next) => setTimeout(() => actions.showGuide(next, '.tutorial-clue', 'Pahami cara mengerjakannya.', ['-10px', '0']), 2000) },
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => actions.showPointer(next, '.first-number', 'Masukkan Angka') },
        { action: (next) => actions.showPointer(next, '2') },
        { action: (next) => actions.showPointer(next, '.second-number') },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction']) },
        { action: (next) => actions.showPointer(next, '.btn-fraction', 'Aktifkan mode pecahan')},
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction']) },
        { action: (next) => actions.showSwapArrow(next, '.division-pair', 'toTop') },
        { action: (next) => actions.showPointer(next, '2', 'Tukar penyebut menjadi pembilang') },
        { action: (next) => actions.removeElement(next, ['.swap-arrow', '.tutorial-instruction']) },
        { action: (next) => setTimeout(() => actions.showSwapArrow(next, '.division-pair', 'toBottom'), 1000) },
        { action: (next) => actions.showPointer(next, '.second-fraction__denominator', 'Dan pembilang menjadi penyebut', '.result', '70px') },
        { action: (next) => actions.showPointer(next, '1') },
        { action: (next) => actions.removeElement(next, ['.swap-arrow', '.tutorial-instruction', '.tutorial-clue']) },
        { action: (next) => actions.showPointer(next, '.btn-submit-result__container', 'Submit Jawaban') },
      ],
      9: [
        { action: (next) => actions.focus(next, ['.sub-quiz']) },
        { action: (next) => setTimeout(() => actions.showArrowMultiplication(next, '.multiplication-pair','top', 1), 1500) },
        { action: (next) => actions.showPointer(next, '4', 'Masukkan hasil perkalian') },
        { action: (next) => actions.removeElement(next, ['.curved-line']) },
        { action: (next) => actions.showPointer(next, '.first-fraction__denominator') },
        { action: (next) => actions.showPointer(next, '1') },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction']) },
        { action: (next) => actions.showPointer(next, '.btn-submit-result__container', 'Submit Jawaban') },
      ],
      10: [
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => setTimeout(() => actions.showClue(next, 'Pecahan <span id="fractionClue"><span id="fraction"><span class="numerator">4</span><span class="denominator">1</span></span></span> artinya 4 ÷ 1. <br/> Kalau bisa dibagi, berarti bisa disederhanakan!', '.result', ['unset', '150px']), 1000) },
        { action: (next) => setTimeout(() => actions.showGuide(next, '.tutorial-clue', 'Sudah paham?', ['-10px', '0']), 4500) },
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => actions.showPointer(next, '.answer-choices .yes', 'Pilih jawaban yang tepat.') }
      ],
      11: [
        { action: (next) => actions.showPointer(next, '.option:nth-child(1)', 'Pilih jawaban yang tepat.', '.result', '70px') }
      ],
      12: [
        { action: (next) => actions.showPointer(next, '.option-a', 'Pilih ilustrasi yang tepat.', '.result', '110px') }
      ]
    },
    3: {
      13: [
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => setTimeout(() => actions.focus(next, ['.gl-progress-bar']), 1000) },
        { action: (next) => setTimeout(() => actions.showGuide(next, '.gl-progress-bar', 'Di level ini kamu memanen <b>padi</b>! 🌾<br>Jawab soal dengan benar untuk mendapatkan <b>bibit padi</b>.<br>Semakin banyak bibit, padi kamu akan tumbuh!', ['0', 'unset']), 1000) },
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => actions.unfocus(next) },
        { action: (next) => setTimeout(() => actions.showClue(next, 'Cara mengubah pecahan campuran ke biasa:', '.result .calc-input', ['unset', 'calc(100% + 50px)']), 1000) },
        { action: (next) => actions.addClueList(next, 'Kalikan angka bulat dengan penyebut <br> <b>2 x 4 = 8</b>') },
        { action: (next) => actions.showArrowMultiplication(next, '.calc-result .fraction-wrapper.mixed', 'bottom', 0, 'conversion') },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.tutorial-clue:last-child'), 2000) },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue .clue-list li']) },
        { action: (next) => actions.showArrowMultiplication(next, '.calc-result .fraction-wrapper.mixed', 'top', 0, 'conversion') },
        { action: (next) => actions.addClueList(next, 'Tambahkan hasilnya dengan pembilang <br> <b>8 + 3 = <span class="result">11</span></b>') },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.tutorial-clue:last-child'), 1000) },
        { action: (next) => actions.showPointer(next, '.first-fraction__numerator', 'Masukkan hasil') },
        { action: (next) => actions.checkInput(next, '.fraction-question #numerator', '11') },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue .clue-list li', '.curved-line.arrow.fraction-conversion']) },
        { action: (next) => actions.addClueList(next, 'Penyebut tetap sama') },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.tutorial-clue:last-child'), 1000) },
        { action: (next) => actions.showArrowMultiplication(next, '.calc-result .fraction-wrapper.mixed', 'bottom', 0, 'operation') },
        { action: (next) => actions.showPointer(next, '.first-fraction__denominator') },
        { action: (next) => actions.checkInput(next, '.fraction-question #denominator', '4', true) },
        { action: (next) => actions.removeElement(next, ['.right-arrow_multiplication', '.tutorial-clue', '.tutorial-instruction']) },
        { action: (next) => actions.showPointer(next, '.btn-submit-result__container', 'Submit Jawaban') },
      ],
      14: [
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => actions.focus(next, ['.gl-progress-bar .gl-minor-progress']) },
        { action: (next) => actions.showGuide(next, '.gl-minor-progress', 'Jawabanmu benar! Bibit padi didapat dan padimu bertumbuh! 🎉', ['unset', '0']) },
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => setTimeout(() => actions.showClue(next, 'Cara mengubah pecahan biasa ke campuran:', '.result .calc-input', ['unset', 'calc(100% + 50px)']), 1000) },
        { action: (next) => actions.addClueList(next, 'Bagi pembilang dengan penyebut <br> <b>5 : 4 = 1 -> Sisa 1</b>') },
        { action: (next) => actions.showArrowMultiplication(next, '.calc-result .fraction-wrapper', 'top-to-bottom', 1, 'conversion') },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.tutorial-clue:last-child'), 2000) },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue .clue-list li']) },
        { action: (next) => actions.addClueList(next, '<b>5 : 4 = <span class="result">1</span> -> Sisa 1</b> <br> Hasil bagi jadi angka bulat') },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.tutorial-clue:last-child'), 1000) },
        { action: (next) => actions.showPointer(next, '.integer', 'Masukkan hasil bagi', '.result', '70px') },
        { action: (next) => actions.checkInput(next, '.fraction-question #integer', '1') },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue .clue-list li', '.tutorial-instruction']) },
        { action: (next) => actions.addClueList(next, '<b>5 : 4 = 1 -> Sisa <span class="result">1</span></b> <br> Sisa hasil bagi jadi pembilang baru.') },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.tutorial-clue:last-child'), 1000) },
        { action: (next) => actions.showPointer(next, '.first-fraction__numerator', 'Masukkan sisa bagi', '.result', '30px') },
        { action: (next) => actions.checkInput(next, '.fraction-question #numerator', '1') },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue .clue-list li', '.tutorial-instruction']) },
        { action: (next) => actions.addClueList(next, 'Penyebut tetap sama.') },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.tutorial-clue:last-child'), 1000) },
        { action: (next) => actions.showPointer(next, '.first-fraction__denominator', 'Masukkan angka pembilang', '.result', '30px') },
        { action: (next) => actions.checkInput(next, '.fraction-question #denominator', '4') },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue__wrapper', '.tutorial-instruction', '.curved-arrow.arrow.to-bottom']) },
        { action: (next) => actions.showPointer(next, '.btn-submit-result__container', 'Submit Jawaban') },
      ],
      15: [
        { action: (next) => setTimeout(() => actions.showClue(next, 'Cara mengubah desimal ke pecahan:', '.result', ['unset', 'calc(100% + 100px)']), 1000) },
        { action: (next) => actions.addClueList(next, 'Tulis 1 di bawah, lalu tambahkan 0 sesuai angka di belakang koma') },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.tutorial-clue:last-child'), 2000) },
        { action: (next) => actions.showPointer(next, '.first-fraction__denominator', 'Masukkan angka 1 dahulu', '.result', '30px') },
        { action: (next) => actions.checkInput(next, '.first-fraction__denominator .number-input.show', '1') },
        { action: (next) => actions.showDoubleCurvedLine(next, '.decimal') },
        { action: (next) => actions.addHelperText(next, '.fraction-question', 'Ada dua angka di belakang koma, jadi tambahkan dua 0 di penyebut', ['60px', '-30px']) },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction']) },
        { action: (next) => actions.showPointer(next, null, 'Masukkan angka', '.result', '30px') },
        { action: (next) => actions.checkInput(next, '.first-fraction__denominator.number-input', '100', true) },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue .clue-list li', '.help-text', '.double-curved', '.tutorial-instruction']) },
        { action: (next) => actions.addClueList(next, 'Hilangkan koma, jadikan angka bulat sebagai pembilang') },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.tutorial-clue:last-child'), 1000) },
        { action: (next) => actions.showArrowMultiplication(next, '.fraction-question', 'to-top-left', 0, 'common', ['8px', '0']) },
        { action: (next) => actions.addHelperText(next, '.fraction-question', '<span id="typing"></span>', ['-5px', '-35px']) },
        { action: (next) => actions.typingLoop(next, ['0,25', '025', '25']) },
        { action: (next) => actions.showPointer(next, '.first-fraction__numerator', 'Masukkan angka', '.result', '30px') },
        { action: (next) => actions.checkInput(next, '.first-fraction__numerator.number-input', '25') },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue .clue-list li', '.help-text', '.arrow-line', '.tutorial-instruction']) },
        { action: (next) => actions.addClueList(next, 'Sederhakan pecahan jika masih bisa dibagi dengan angka yang sama. <br> Tips: Gunakan FPB untuk mencari pembagi') },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.tutorial-clue:last-child'), 2000) },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue .clue-list li']) },
        { action: (next) => actions.addClueList(next, 'FPB 25 dan 100 adalah 25. Bagi keduanya dengan 25') },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.tutorial-clue:last-child'), 1500) },
        { action: (next) => setTimeout(() => actions.addHelperText(next, '.fraction-container', '25 : 25 = <span class="result">1</span>', ['-15px', '-20px']), 500) },
        { action: (next) => setTimeout(() => actions.addHelperText(next, '.fraction-container', '100 : 25 = <span class="result">4</span>', ['calc(100% + 5px)', '-20px']), 1000) },
        { action: (next) => setTimeout(() => actions.showPointer(next, '.btn-add-result', 'Tambahkan input hasil', '.result', '30px', '-10px'), 1000) },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction']) },
        { action: (next) => setTimeout(() => actions.showPointer(next, '.switch-input-mode', 'Ubah ke mode pecahan', '.result', '30px', '-15px'), 1000) },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction ']) },
        { action: (next) => setTimeout(() => actions.showPointer(next, '.first-fraction__numerator', 'Masukkan hasil bagi'), 1000) },
        { action: (next) => actions.checkInput(next, '.first-fraction__numerator.number-input', '1') },
        { action: (next) => actions.showPointer(next, '.first-fraction__denominator') },
        { action: (next) => actions.checkInput(next, '.first-fraction__denominator.number-input', '4') },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction', '.tutorial-clue__wrapper', '.help-text']) },
        { action: (next) => actions.showPointer(next, '.btn-submit-result__container', 'Submit jawaban') },
      ],
      16: [
        { action: (next) => setTimeout(() => actions.showClue(next, 'Cara mengubah pecahan ke desimal:', '.result', ['unset', 'calc(100% + 100px)']), 1000) },
        { action: (next) => actions.addClueList(next, 'Lihat penyebut, Jika bisa dijadikan kelipatan 10 (10, 100, 1000, …), ubah dulu') },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.tutorial-clue:last-child', 'Lanjut'), 2000) },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue .clue-list li']) },
        { action: (next) => actions.addClueList(next, 'Jika tidak bisa, cukup bagi pembilang dengan penyebut.') },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.tutorial-clue:last-child', 'Oke, paham.'), 2000) },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue .clue-list li']) },
        { action: (next) => actions.addClueList(next, '5 bisa diubah ke 10 dengan cara dikali 2. <br> 5 x <span class="result">2</span> = 10') },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.tutorial-clue:last-child', 'Oke, mengerti.'), 2000) },
        { action: (next) => actions.showPointer(next, '.first-fraction__denominator.number-input', 'Masukkan angka pengali', '.result', '30px') },
        { action: (next) => actions.checkInput(next, '.first-fraction__denominator.number-input', '2') },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue .clue-list li', '.tutorial-instruction']) },
        { action: (next) => actions.addClueList(next, 'Kalikan pembilang dengan angka yang sama.') },
        { action: (next) => actions.showPointer(next, '.first-fraction__numerator.number-input', 'Masukkan angka pengali', '.result', '30px') },
        { action: (next) => actions.checkInput(next, '.first-fraction__numerator.number-input', '2') },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue .clue-list li', '.tutorial-instruction']) },
        { action: (next) => actions.addClueList(next, 'Hitung hasil perkaliannya.') },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.tutorial-clue:last-child', 'Oke, mengerti.'), 1000) },
        { action: (next) => actions.showPointer(next, '.btn-add-result', 'Tambahkan input hasil', '.result', '30px', '-10px') },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction', '.tutorial-clue__wrapper']) },
        { action: (next) => actions.showClue(next, 'Cara mengubah pecahan ke desimal:', '.result', ['unset', 'calc(100% + 120px)']) },
        { action: (next) => actions.addClueList(next, 'Hitung hasil perkaliannya.') },
        { action: (next) => setTimeout(() => actions.showPointer(next, '.switch-input-mode', 'Ubah ke mode pecahan', '.result', '30px', '-15px'), 500) },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction ']) },
        { action: (next) => setTimeout(() => actions.showPointer(next, '.first-fraction__numerator', 'Masukkan hasil perkalian'), 1000) },
        { action: (next) => actions.checkInput(next, '.first-fraction__numerator.number-input', '14') },
        { action: (next) => actions.showPointer(next, '.first-fraction__denominator') },
        { action: (next) => actions.checkInput(next, '.first-fraction__denominator.number-input', '10') },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue .clue-list li', '.tutorial-instruction']) },
        { action: (next) => actions.addClueList(next, 'Tentukan bentuk desimalnya.') },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.tutorial-clue:last-child', 'Oke, mengerti.'), 1000) },
        { action: (next) => actions.showPointer(next, '.btn-add-result', 'Tambahkan input hasil', '.result', '30px', '-10px') },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction', '.tutorial-clue__wrapper']) },
        { action: (next) => actions.showClue(next, 'Cara mengubah pecahan ke desimal:', '.result', ['unset', 'calc(100% + 130px)']) },
        { action: (next) => actions.addClueList(next, 'Tulis dulu angka pembilangnya lalu geser koma dari kanan ke kiri sebanyak 0 pada penyebut. <br> Tips: Gunakan tombol panah bantuan untuk menentukan koma.') },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.tutorial-clue:last-child', 'Oke, mengerti.'), 1000) },
        { action: (next) => setTimeout(() => actions.showPointer(next, '.decimal', 'Masukkan hasil', '.result', '30px', '-5px'), 500) },
        { action: (next) => actions.checkInput(next, '.decimal.number-input', '14') },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction']) },
        { action: (next) => actions.showPointer(next, '.retreat-btn', 'Pindah koma ke kiri satu kali', '.result', '65px', '5px') },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction', '.tutorial-clue__wrapper']) },
        { action: (next) => actions.showPointer(next, '.btn-submit-result__container', 'Submit jawaban') },
      ]
    }
  }
}

export default tutorialData;