import { createGlIllustrationOverlayA, createGlIllustrationOverlayB } from "../views/templates/template-creator";
import mainQuiz from "./main-quiz";
import actions from "./tutorial-actions";

const tutorialData = {
  city01: {
    1: { // Level 1
      1: [ // Step id
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => setTimeout(() => actions.focus(next, ['.gl-progress-bar']), 1000) },
        { action: (next) => setTimeout(() => actions.showGuide(next, '.gl-progress-bar', 'Kemajuan game ditampilkan di bar ini. </br> Kamu akan mengumpulkan <b>air</b> supaya tanaman bisa berkembang. <br> <b>Air</b> bisa kamu dapatkan dari menjawab soal dengan benar!', ['0', 'unset']), 1000) },
        { action: (next) => actions.showGuide(next, '.gl-progress-bar', 'Tanda melingkar sebagai tanda posisi step yang sedang dikerjakan', ['unset', '0']) },
        { action: (next) => actions.focus(next, ['.main-quiz']) },
        { action: (next) => setTimeout(() => actions.showGuide(next, '.main-quiz', 'Soal kuis utama. Baca dan pahami sebelum mengerjakan!', ['0', 'unset']), 1000) },
        { action: (next) => actions.focus(next, ['.sub-quiz']) },
        { action: (next) => setTimeout(() => actions.showGuide(next, '.sub-quiz', 'Setiap soal terdapat step-step yang harus dijawab.', ['0', 'unset']), 1000) },
        { action: (next) => actions.showPrecisWrapper(next) },
        { action: (next) => actions.focus(next, ['.precis-wrapper']) },
        { action: (next) => setTimeout(() => actions.highlight(next, '.known', 0), 1000) },
        { action: (next) => {
          const mainQuiz = (JSON.parse(sessionStorage.getItem('detailQuiz'))).main;
          const tutorialQuiz = mainQuiz[0];
          setTimeout(() => actions.showPrecis(next, tutorialQuiz.precis, 0), 1000); 
        } },
        { action: (next) => setTimeout(() => actions.highlight(next, '.known', 1), 2000) },
        { action: (next) => {
          const mainQuiz = (JSON.parse(sessionStorage.getItem('detailQuiz'))).main;
          const tutorialQuiz = mainQuiz[0];
          setTimeout(() => actions.showPrecis(next, tutorialQuiz.precis, 1), 1000);
        } },
        { action: (next) => setTimeout(() => actions.showGuide(next, '.precis-wrapper', 'Catat informasi penting dari soal.', ['unset', '0']), 1000) },
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => actions.unfocus(next) },
        { action: (next) => setTimeout(() => actions.showPointer(next, '.btn-fraction', 'Aktifkan mode pecahan', '.result', '30px', true), 2000) },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction']) },
        { action: (next) => actions.showPointer(next, '2', 'Masukkan angka perkalian') },
        { action: (next) => actions.showPointer(next, '.first-fraction__denominator') },
        { action: (next) => actions.showPointer(next, '3') },
        { action: (next) => actions.showPointer(next, '.second-number') },
        { action: (next) => actions.showPointer(next, '5') },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction']) },
        { action: (next) => actions.showPointer(next, '.btn-submit-result__container', 'Submit Jawaban') },
      ],
      2: [
        { action: (next) => actions.removeHighlight(next) },
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => actions.focus(next, ['.gl-progress-bar .gl-minor-progress']) },
        { action: (next) => actions.showGuide(next, '.gl-minor-progress', 'Jawabanmu benar! Air didapat dan tanamanmu bertumbuh! 😊', ['unset', '0']) },
        { action: (next) => actions.focus(next, ['.gl-progress-bar', '.main-quiz', '.sub-quiz']) },
        { action: (next) => actions.focus(next, ['.multiplication-pair']) },
        { action: (next) => setTimeout(() => actions.showArrowMultiplication(next, 'top'), 2000) },
        { action: (next) => setTimeout(() => actions.showClue(next, 'Kalikan angka atas dengan 5. <span class="multiplication">2 x 5 = 10</span>', '.result .calc-input', ['unset', '100%']), 1000) },
        { action: (next) => setTimeout(() => actions.showGuide(next, '.tutorial-clue', 'Perhatikan cara mengerjakannya.', ['unset', '0']), 2000) },
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => setTimeout(() => actions.showPointer(next, '1', 'Masukkan hasil perkalian', '.result', '30px', true), 1000)},
        { action: (next) => actions.showPointer(next, '0')},
        { action: (next) => actions.removeElement(next, ['.tutorial-clue', '.curved-line', '.tutorial-instruction']) },
        { action: (next) => setTimeout(() => actions.showClue(next, 'Berikan angka penyebut ke hasil', '.result .calc-input', ['unset', '100%']), 1000) },
        { action: (next) => actions.showArrowMultiplication(next, 'bottom') },
        { action: (next) => actions.showPointer(next, '.first-fraction__denominator') },
        { action: (next) => actions.showPointer(next, '3') },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue', '.right-arrow_multiplication', '.tutorial-instruction']) },
        { action: (next) => actions.showPointer(next, '.btn-submit-result__container', 'Submit Jawaban') },
      ],
      3: [
        { action: (next) => actions.unfocus(next) },
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => actions.focus(next, ['.sub-quiz', '.fraction.result']) },
        { action: (next) => setTimeout(() => actions.showClue(next, 'Pecahan bisa disederhanakan jika angka atas dan bawah bisa dibagi dengan angka yang sama. Kalau tidak bisa, berarti pecahannya sudah paling sederhana.', '.result', ['unset', '50px']), 2000) },
        { action: (next) => actions.addBtnNext(next, '.tutorial-clue') },
        { action: (next) => actions.showClue(next, '10 dan 3 tidak dapat dibagi dengan angka yang sama (>1), <b>jadi tidak bisa disederhanakan lagi.</b>', '.result', ['85px', '-60px']) },
        { action: (next) => actions.addBtnNext(next, '.tutorial-clue:last-child') },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue:first-child', '.tutorial-clue:last-child']) },
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => actions.showPointer(next, '.answer-choices .no', 'Pilih jawaban yang tepat.') }
      ],
      5: [
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => actions.focus(next, ['.fraction.result', '.fraction-unit']) },
        { action: (next) => setTimeout(() => actions.showClue(next, 'Bayangkan, ada keranjang buah yang tiap keranjangnya berisi 3 bagian yang sama.', '.result', ['0', '60px']), 2000) },
        { action: (next) => setTimeout(() => actions.showClue(next, 'Dan kamu punya buah-buahan yang bisa mengisi 10 bagian keranjang.', '.result', ['120px', '70px']), 3000) },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.tutorial-clue:last-child', 'Lanjut'), 1500) },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue__wrapper']) },
        { action: (next) => actions.showClue(next, 'Jadi, keranjang yang dipakai berjumlah:', '.result', ['0', '60px']) },
        { action: (next) => actions.addBtnNext(next, '.tutorial-clue:last-child', 'Lanjut') },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue__wrapper']) },
        { action: (next) => actions.showClue(next, '3 keranjang buah (9 bagian)', '.result', ['0', '60px']) },
        { action: (next) => setTimeout(() => actions.showIllustrationContainer(next), 1500) },
        { action: (next) => setTimeout(() => actions.addItemToContainer(next, '.illustration-container', '<img src="./illustrations-quiz/gl-il-1.png">'), 1500) },
        { action: (next) => setTimeout(() => actions.addItemToContainer(next, '.illustration-container', '<img src="./illustrations-quiz/gl-il-1.png">'), 1000) },
        { action: (next) => setTimeout(() => actions.addItemToContainer(next, '.illustration-container', '<img src="./illustrations-quiz/gl-il-1.png">'), 1000) },
        { action: (next) => setTimeout(() => actions.showClue(next, '1 keranjang buah (1 bagian/tidak penuh)', '.result', ['60px', '70px']), 1500) },
        { action: (next) => setTimeout(() => actions.addItemToContainer(next, '.illustration-container', '<img src="./illustrations-quiz/gl-il-2.png">'), 1500) },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.tutorial-clue:last-child', 'Lanjut') , 1000) },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue__wrapper']) },
        { action: (next) => actions.showClue(next, 'Jadi, ilustrasinya yaitu 3 keranjang penuh + 1 keranjang berisi 1 bagian.', '.result', ['0', '60px']) },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.tutorial-clue:last-child') , 1000) },
        { action: (next) => actions.removeElement(next, ['.tutorial-clue__wrapper', '.illustration-container']) },
        { action: (next) => actions.unfocus(next, ['.fraction.result', '.item-name']) },
        { action: (next) => actions.focus(next, ['.open-image-btn']) },
        { action: (next) => actions.showPointer(next, '.open-image-btn.first', 'Klik kaca pembesar untuk melihat gambar ukuran penuh') },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction']) },
        { action: (next) => actions.hideElement(next, '#imageModal .close-btn') },
        { action: (next) => setTimeout(() => actions.showDialog(next, '.modal-content', 'Apakah ilustrasi ini menggambarkan 10/3 keranjang buah?', 'top'), 1500) },
        { action: (next) => setTimeout(() => actions.showDialog(next, '.modal-content', 'Mari kita cek bersama!', 'bottom'), 2000) },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.dialog-tutorial.bottom', 'Oke, mulai!'), 1500) },
        { action: (next) => actions.addOverlay(next, '.modal-content', createGlIllustrationOverlayA()) },
        { action: (next) => actions.showAllElementsGradually(next, '.number-counter span:not(.empty)') },
        { action: (next) => setTimeout(() => actions.showDialog(next, '.modal-content', 'Ilustrasi di atas menunjukkan 11 bagian keranjang dan setiap keranjang berisi 3 bagian, sehingga bentuk pecahannya adalah 11/3.', 'bottom'), 1500) },
        { action: (next) => setTimeout(() => actions.showArrowNextBtn(next, '.dialog-tutorial.bottom'), 2000) },
        { action: (next) => actions.removeElement(next, ['.dialog-tutorial.bottom']) },
        { action: (next) => actions.showDialog(next, '.modal-content', 'Jadi, ilustrasi di atas bukan jawaban yang tepat.', 'bottom') },
        { action: (next) => setTimeout(() => actions.showElement(next, '#imageModal .close-btn'), 2000) },
        { action: (next) => actions.showPointer(next, '.close-btn', 'Klik untuk menutup detail gambar.', '.finger-container') },
        { action: (next) => actions.removeElement(next, ['.dialog-tutorial', '.illustration-overlay']) },
        { action: (next) => actions.unfocus(next) },
        { action: (next) => actions.focus(next, ['.open-image-btn.second']) },
        { action: (next) => actions.showPointer(next, '.open-image-btn.second', 'Klik kaca pembesar untuk melihat gambar lebih detail') },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction']) },
        { action: (next) => actions.hideElement(next, '#imageModal .close-btn') },
        { action: (next) => setTimeout(() => actions.showDialog(next, '.modal-content', 'Apakah ilustrasi ini menggambarkan 10/3 keranjang buah?', 'top'), 1500) },
        { action: (next) => setTimeout(() => actions.showDialog(next, '.modal-content', 'Mari kita cek bersama!', 'bottom'), 2000) },
        { action: (next) => setTimeout(() => actions.addBtnNext(next, '.dialog-tutorial.bottom', 'Oke, mulai!'), 1500) },
        { action: (next) => actions.addOverlay(next, '.modal-content', createGlIllustrationOverlayB()) },
        { action: (next) => actions.showAllElementsGradually(next, '.number-counter span:not(.empty)') },
        { action: (next) => setTimeout(() => actions.showDialog(next, '.modal-content', 'Ilustrasi di atas menunjukkan 10 bagian keranjang dan setiap keranjang berisi 3 bagian, sehingga bentuk pecahannya adalah 10/3.', 'bottom'), 1500) },
        { action: (next) => setTimeout(() => actions.showArrowNextBtn(next, '.dialog-tutorial.bottom'), 2000) },
        { action: (next) => actions.removeElement(next, ['.dialog-tutorial.bottom']) },
        { action: (next) => actions.showDialog(next, '.modal-content', 'Jadi, ilustrasi di atas adalah jawaban yang tepat.', 'bottom') },
        { action: (next) => setTimeout(() => actions.showElement(next, '#imageModal .close-btn'), 2000) },
        { action: (next) => actions.showPointer(next, '.close-btn', 'Klik untuk menutup detail gambar.', '.finger-container') },
        { action: (next) => actions.removeElement(next, ['.dialog-tutorial', '.illustration-overlay']) },
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => actions.showPointer(next, '.answer-choices .option-b', 'Pilih jawaban yang tepat.', '.result', '120px') }
      ]
    },
    2: { // Level 2
      7: [ // Step 1
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => setTimeout(() => actions.focus(next, ['.gl-progress-bar']), 1000) },
        { action: (next) => setTimeout(() => actions.showGuide(next, '.gl-progress-bar', 'Di level ini kamu akan mengumpulkan jamur yang memiliki berbagai tingkatan. Kumpulkan spora dengan menjawab pertanyaan dengan benar untuk meningkatkan level jamur! ', ['0', 'unset']), 1000) },
        { action: (next) => actions.showGuide(next, '.gl-progress-bar', 'Tanda melingkar sebagai tanda posisi step yang sedang dikerjakan.', ['unset', '0']) },
        { action: (next) => actions.focus(next, ['.main-quiz']) },
        { action: (next) => setTimeout(() => actions.showGuide(next, '.main-quiz', 'Soal kuis utama. Baca dan pahami sebelum mengerjakan!', ['0', 'unset']), 1000) },
        { action: (next) => actions.focus(next, ['.sub-quiz']) },
        { action: (next) => setTimeout(() => actions.showGuide(next, '.sub-quiz', 'Setiap soal terdapat step-step yang harus dijawab.', ['0', 'unset']), 1000) },
        { action: (next) => actions.showPrecisWrapper(next) },
        { action: (next) => actions.focus(next, ['.precis-wrapper']) },
        { action: (next) => setTimeout(() => actions.highlight(next, '.known', 0), 1000) },
        { action: (next) => {
          const mainQuiz = (JSON.parse(sessionStorage.getItem('detailQuiz'))).main;
          const tutorialQuiz = mainQuiz[0];
          setTimeout(() => actions.showPrecis(next, tutorialQuiz.precis, 0), 1000); 
        } },
        { action: (next) => setTimeout(() => actions.highlight(next, '.known', 1), 2000) },
        { action: (next) => {
          const mainQuiz = (JSON.parse(sessionStorage.getItem('detailQuiz'))).main;
          const tutorialQuiz = mainQuiz[0];
          setTimeout(() => actions.showPrecis(next, tutorialQuiz.precis, 1), 1000); 
        } },
        { action: (next) => setTimeout(() => actions.showGuide(next, '.precis-wrapper', 'Catat informasi penting dari soal.', ['unset', '0']), 1000) },
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => actions.unfocus(next) },
        { action: (next) => actions.showPointer(next, '.first-number', 'Masukkan angka pembagian') },
        { action: (next) => actions.showPointer(next, '2') },
        { action: (next) => actions.showPointer(next, '.second-number') },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction']) },
        { action: (next) => actions.showPointer(next, '.btn-fraction', 'Aktifkan mode pecahan', '.result', '30px') },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction']) },
        { action: (next) => actions.showPointer(next, '1') },
        { action: (next) => actions.showPointer(next, '.second-fraction__denominator', 'Masukkan angka', '.result', '50px') },
        { action: (next) => actions.showPointer(next, '2') },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction']) },
        { action: (next) => actions.showPointer(next, '.btn-submit-result__container', 'Submit Jawaban') },
      ],
      8: [
        { action: (next) => actions.removeHighlight(next) },
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => actions.focus(next, ['.gl-progress-bar .gl-minor-progress']) },
        { action: (next) => actions.showGuide(next, '.gl-minor-progress', 'Jawabanmu benar! Spora didapat dan jamurmu meningkat!😊', ['unset', '0']) },
        { action: (next) => actions.focus(next, ['.division-pair']) },
        { action: (next) => setTimeout(() => actions.showClue(next, 'Untuk mengubah menjadi perkalian, balik pecahan pembagi. Yang atas menjadi di bawah, dan bawah menjadi di atas.', '.result .calc-input', ['unset', 'calc(100% + 80px)']), 1000) },
        { action: (next) => setTimeout(() => actions.showGuide(next, '.tutorial-clue', 'Pahami cara mengerjakannya.', ['-10px', '0']), 2000) },
        { action: (next) => actions.toggleOverlay(next) },
        { action: (next) => actions.showPointer(next, '.first-number', 'Masukkan Angka') },
        { action: (next) => actions.showPointer(next, '2') },
        { action: (next) => actions.showPointer(next, '.second-number') },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction']) },
        { action: (next) => actions.showPointer(next, '.btn-fraction', 'Aktifkan mode pecahan')},
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction']) },
        { action: (next) => actions.showSwapArrow(next, '.division-pair', 'toTop') },
        { action: (next) => actions.showPointer(next, '2', 'Tukar penyebut menjadi pembilang') },
        { action: (next) => actions.removeElement(next, ['.swap-arrow', '.tutorial-instruction']) },
        { action: (next) => setTimeout(() => actions.showSwapArrow(next, '.division-pair', 'toBottom'), 1000) },
        { action: (next) => actions.showPointer(next, '.second-fraction__denominator', 'Dan pembilang menjadi penyebut', '.result', '70px') },
        { action: (next) => actions.showPointer(next, '1') },
        { action: (next) => actions.removeElement(next, ['.swap-arrow', '.tutorial-instruction', '.tutorial-clue']) },
        { action: (next) => actions.showPointer(next, '.btn-submit-result__container', 'Submit Jawaban') },
      ],
      9: [
        { action: (next) => setTimeout(() => actions.showArrowMultiplication(next, 'top', 1), 1500) },
        { action: (next) => actions.showPointer(next, '4', 'Masukkan hasil perkalian') },
        { action: (next) => actions.removeElement(next, ['.curved-line']) },
        { action: (next) => actions.showPointer(next, '.first-fraction__denominator') },
        { action: (next) => actions.showPointer(next, '1') },
        { action: (next) => actions.removeElement(next, ['.tutorial-instruction']) },
        { action: (next) => actions.showPointer(next, '.btn-submit-result__container', 'Submit Jawaban') },
      ],
      10: [
        { action: (next) => setTimeout(() => actions.showClue(next, 'Pecahan <span id="fractionClue"><span id="fraction"><span class="numerator">4</span><span class="denominator">1</span></span></span> artinya 4 ÷ 1. <br/> Bila pecahan bisa dibagi, berarti pecahan bisa disederhanakan.', '.result', ['unset', '150px']), 1000) },
      ],
      11: [
        { action: (next) => actions.showPointer(next, '.', 'Masukkan hasil perkalian') },
      ]
    }
  }
}

export default tutorialData;